# Site settings
title: Prose Prism
description: "An Informative Website"
url: ""
author:
  name: "Prose Prism"
  email: "proseprism@gmail.com"
  url: "http://www.proseprism.com"

# Build settings
baseurl: "" # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /proseprism/:title/
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

plugins: [jekyll-paginate]

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: true
